pipeline {
    agent any
    stages {
        stage("deploy"){
            steps {
                sh "docker run -it --rm zeronetdev/rampup-provcli echo ${params.TAG}"
            }
        }
    }
}