pipeline {
    agent {
        docker { 
            image 'zeronetdev/rampup-provcli:0.0.1'
            args '-v /home/ubuntu/RampUp/ansible/playbooks:/playbooks -v /home/ubuntu/.aws:/root/.aws'
        }
    }
    stages {
        stage("deploy"){
            steps {
                dir("/playbooks"){
                    sh "ls"
                    sh "ansible -i inventory_aws_ec2.yml -m ping"
                }
                sh "echo ${params.TAG}"
            }
        }
    }
}