pipeline {
    agent any
    environment {
        HOME = '.'
        PROJECT = "zeronetdev/rampup-front"
        container = null
        failed_stage = null
    }
    stages {
        stage("build front image"){
            steps {
                script {
                    container = docker.build(PROJECT)
                }
            }
            post {
                failure {
                    script {
                        failed_stage = "build image"
                    }
                }
            }
        }
        stage("push image"){
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        container.push("${BUILD_NUMBER}")
                    }
                }
            }
            post {
                failure {
                    script {
                        failed_stage = "push image"
                    }
                }
            }
        }
        stage("clean") {
            steps {
                sh "for image in \$(docker images | grep ${env.PROJECT} | awk \'{print \$3}\'| uniq); do docker rmi -f \$image; done"
            }
            post {
                failure {
                    script {
                        failed_stage = "clean"
                    }
                }
            }
        }
        stage("trigger CD"){
            script {
                build job: 'CD', parameters: [string(name: 'TAG', value: "${BUILD_NUMBER}")]
            }
            post {
                failure {
                    script {
                        failed_stage = "trigger CD"
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                mail to: 'carlos.lizalda1@gmail.com',
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL} on ${failed_stage} stage"
            }
        }
    }
}