pipeline {
    agent any
    environment {
        HOME = '.'
        container = null
        TAG = """${sh(returnStdout: true, script: 'date +%s%N')}"""
        PROJECT = "zeronetdev/rampup-front"
    }
    stages {
        stage("build front image"){
            steps {
                script {
                    container = docker.build(PROJECT)
                }
            }
        }
        stage("push image"){
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                        container.push("${TAG}")
                    }
                }
            }
        }
        stage("clean") {
            steps {
                sh 'for image in \$(sudo docker images | grep ${env.PROJECT} | awk \'{print \$2}\'| uniq); do sudo docker rmi -f \$image; done'
            }
        }
    }
    post {
        failure {
            mail to: 'carlos.lizalda1@gmail.com',
                subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
                body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}